### PR TITLE
Added a better motion detection algorithm

### PR DESCRIPTION
**Pull request by thomas-pegot**
- Changed the motion detection algorithm by including this lib: https://github.com/thomas-pegot/esp32-motion
- fixed webserver not responding
- Workaround memory limitation
- fixed display offset on \n

Motion detection  time ~35ms for ~ 30k samples.

### CODE REVIEW

**Comment by s60sc** [comment]
Thanks for your proposal. I will first do some research and testing to understand how the alternative algorithm performs.

**Comment by s60sc** [comment]
Hi - I installed your pull request and tested it but found it to be slower, which impacts the achievable frame rate. Times below in ms for svga image

|                        |  yours    |  mine |
|----------------|----------|--------|
|jpeg decode:  |     450     |      110|
|motion detect:  |    35       |        4|
|total:                 |  485       |     114|

Yours does use a bigger sample size (30000 vs 3000) which will increase the processing required.

I am considering changing my algorithm to do background subtraction instead of mass shift.

**Comment by thomas-pegot** [comment]
Yeah you have no notion of computer vision and image processing.
I use real [motion estimation algorithm](https://en.wikipedia.org/wiki/Motion_estimation) used in mpeg4 codec ...

You use no more than averaging the image pretending to be center of mass which is mainly used in physics. This algorithm would work if you perform an object detection first and then apply center of mass algo. 

Your detection activate everytime just due to artefact or light change or any noise because it isn't a motion detection algorithm.

Take the same input:

3000 samples:

|  |  yours | mine |
|---|---|---|
|jpeg decode (input)| 110| 110|
|motion detect| 4| 4|

But 3000 samples are completely irrelevant


I can't tell if you are being hypocrite or you don't understand what I have done.

If you want 3000 samples you know what to do (change scale in framesize) and it will achieve ~2ms. 
We are in computer vision not signal processing : 3000 samples is the size of the image flattened... Do you really think you can estimate a motion with a 20 x 15 image (20*15=3000)?? 

Look at the state of the art of existing [motion detection algorithm](https://en.wikipedia.org/wiki/Motion_estimation). You said you will do some research apparently you didn't.

**Comment by s60sc** [comment]
The algorithm I use is for the camera to simply act as a PIR, not for object tracking. I accept that the algorithms you use are more sophisticated.

**Comment by thomas-pegot** [comment]
Except an image is not equivalent to signal from PIR especially. Especially a jpeg image.
As I mentioned use algorithm to the relevant field. 
Your algorithm is actually wrong it is as effective as a rolling dice.
But it's your repo you do w/e you want. 
It's just hurting to see this as an computer vision engineer.

Sophiticated doesn't mean heavier computation. The jpeg codec from the esp32 is very sophisticated but at the end you have better fps and it save lot of memory compared to other format (grayscale, rgb888,...). 

Actually keep your algorithm.
good luck

**Comment by s60sc** [comment]
I respect the work that you have done. I would propose that you clone my repository with your changes. I can add a link to your repository from my README so that others can select which is most appropriate to their requirements.

**Pull request closed without merging**
